//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditoria
    {
        public int id { get; set; }
        public System.DateTimeOffset fecha { get; set; }
        public string accion { get; set; }
        public string schema { get; set; }
        public string tabla { get; set; }
        public string pk { get; set; }
        public string session { get; set; }
        public string user_bd { get; set; }
        public string data { get; set; }
    }
}
