//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class correo_institucional
    {
        public int id { get; set; }
        public Nullable<long> id_session { get; set; }
        public string correo { get; set; }
    
        public virtual user_session user_session { get; set; }
    }
}
