//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class denuncia_publicacion
    {
        public long id { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> id_publicacion { get; set; }
        public Nullable<long> id_denunciante { get; set; }
        public Nullable<int> id_estado { get; set; }
    
        public virtual user_session user_session { get; set; }
        public virtual estado_denuncia estado_denuncia { get; set; }
        public virtual publicacion publicacion { get; set; }
    }
}
