//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ForoUdecEntities1 : DbContext
    {
        public ForoUdecEntities1()
            : base("name=ForoUdecEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contacto> contacto { get; set; }
        public virtual DbSet<denuncia_comentario> denuncia_comentario { get; set; }
        public virtual DbSet<denuncia_publicacion> denuncia_publicacion { get; set; }
        public virtual DbSet<estado_denuncia> estado_denuncia { get; set; }
        public virtual DbSet<controles> controles { get; set; }
        public virtual DbSet<formulario> formulario { get; set; }
        public virtual DbSet<idioma> idioma { get; set; }
        public virtual DbSet<lcontroles> lcontroles { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<comentario> comentario { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<publicacion> publicacion { get; set; }
        public virtual DbSet<puntuacion> puntuacion { get; set; }
        public virtual DbSet<auditoria> auditoria { get; set; }
        public virtual DbSet<bloqueo_configuration> bloqueo_configuration { get; set; }
        public virtual DbSet<ingresos> ingresos { get; set; }
        public virtual DbSet<bloqueo> bloqueo { get; set; }
        public virtual DbSet<correo_institucional> correo_institucional { get; set; }
        public virtual DbSet<estado1> estado1 { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<user_session> user_session { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    
        public virtual ObjectResult<f_caragr_datos_admin_chart_Result> f_caragr_datos_admin_chart()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_caragr_datos_admin_chart_Result>("f_caragr_datos_admin_chart");
        }
    
        public virtual ObjectResult<f_caragr_datos_admin_home_Result> f_caragr_datos_admin_home()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_caragr_datos_admin_home_Result>("f_caragr_datos_admin_home");
        }
    
        public virtual int f_cargar_usuariospoints()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_cargar_usuariospoints");
        }
    
        public virtual ObjectResult<f_cargar_usuariospubl_Result> f_cargar_usuariospubl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_cargar_usuariospubl_Result>("f_cargar_usuariospubl");
        }
    
        public virtual ObjectResult<f_crud_mod_post_Result> f_crud_mod_post(string orden)
        {
            var ordenParameter = orden != null ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_crud_mod_post_Result>("f_crud_mod_post", ordenParameter);
        }
    
        public virtual ObjectResult<f_crud_post_Result> f_crud_post(string orden)
        {
            var ordenParameter = orden != null ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_crud_post_Result>("f_crud_post", ordenParameter);
        }
    
        public virtual ObjectResult<string> f_crud_usuarios_delete(Nullable<int> userid, string session)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_crud_usuarios_delete", useridParameter, sessionParameter);
        }
    
        public virtual ObjectResult<string> f_crud_usuarios_delete2(Nullable<int> id_user)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_crud_usuarios_delete2", id_userParameter);
        }
    
        public virtual ObjectResult<f_crud_usuarios_listar_Result> f_crud_usuarios_listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_crud_usuarios_listar_Result>("f_crud_usuarios_listar");
        }
    
        public virtual ObjectResult<string> f_modificar_perfil(Nullable<int> admin, string session, Nullable<int> userid, string username, string correo, string contrasena)
        {
            var adminParameter = admin.HasValue ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(int));
    
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_modificar_perfil", adminParameter, sessionParameter, useridParameter, usernameParameter, correoParameter, contrasenaParameter);
        }
    
        public virtual ObjectResult<string> f_modificar_perfil_usuario(string session, Nullable<int> userid, string nombre, string apellido, Nullable<int> edad, string sexo)
        {
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(int));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_modificar_perfil_usuario", sessionParameter, useridParameter, nombreParameter, apellidoParameter, edadParameter, sexoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> f_traer_bloqueo_sesiones(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("f_traer_bloqueo_sesiones", usernameParameter);
        }
    
        public virtual ObjectResult<f_traer_datos_perfil_Result> f_traer_datos_perfil(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_traer_datos_perfil_Result>("f_traer_datos_perfil", useridParameter);
        }
    
        public virtual ObjectResult<f_traer_datos_sesion_Result> f_traer_datos_sesion(string userid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_traer_datos_sesion_Result>("f_traer_datos_sesion", useridParameter);
        }
    
        public virtual int f_agregar_contacto(string nombre, string apellido, string correo, string telefono, string contenido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var contenidoParameter = contenido != null ?
                new ObjectParameter("contenido", contenido) :
                new ObjectParameter("contenido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_agregar_contacto", nombreParameter, apellidoParameter, correoParameter, telefonoParameter, contenidoParameter);
        }
    
        public virtual ObjectResult<string> f_modificar_perfil_ajustes(string session, Nullable<int> userid, string username, string correo, string contrasena)
        {
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_modificar_perfil_ajustes", sessionParameter, useridParameter, usernameParameter, correoParameter, contrasenaParameter);
        }
    
        public virtual ObjectResult<string> f_modificar_usuario(string session, Nullable<int> userid, string nombre, string apellido, Nullable<int> edad, string sexo, string avatar)
        {
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(int));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var avatarParameter = avatar != null ?
                new ObjectParameter("avatar", avatar) :
                new ObjectParameter("avatar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_modificar_usuario", sessionParameter, useridParameter, nombreParameter, apellidoParameter, edadParameter, sexoParameter, avatarParameter);
        }
    
        public virtual ObjectResult<string> f_registro_usuario(string username, string contrasena, string correo, string session)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_registro_usuario", usernameParameter, contrasenaParameter, correoParameter, sessionParameter);
        }
    
        public virtual int f_aceptar_denuncia_comentario(Nullable<int> denunciaid)
        {
            var denunciaidParameter = denunciaid.HasValue ?
                new ObjectParameter("denunciaid", denunciaid) :
                new ObjectParameter("denunciaid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_aceptar_denuncia_comentario", denunciaidParameter);
        }
    
        public virtual ObjectResult<string> f_denunciar_comentario(Nullable<int> userid, Nullable<int> comentarioid, string descripcion)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var comentarioidParameter = comentarioid.HasValue ?
                new ObjectParameter("comentarioid", comentarioid) :
                new ObjectParameter("comentarioid", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_denunciar_comentario", useridParameter, comentarioidParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<string> f_denunciar_publicacion(Nullable<int> userid, Nullable<int> postid, string descripcion)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var postidParameter = postid.HasValue ?
                new ObjectParameter("postid", postid) :
                new ObjectParameter("postid", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_denunciar_publicacion", useridParameter, postidParameter, descripcionParameter);
        }
    
        public virtual int f_eliminar_denuncia_comentario(Nullable<int> denunciaid)
        {
            var denunciaidParameter = denunciaid.HasValue ?
                new ObjectParameter("denunciaid", denunciaid) :
                new ObjectParameter("denunciaid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_eliminar_denuncia_comentario", denunciaidParameter);
        }
    
        public virtual ObjectResult<f_mostar_denuncias_comentario_Result> f_mostar_denuncias_comentario(Nullable<int> denunciaid)
        {
            var denunciaidParameter = denunciaid.HasValue ?
                new ObjectParameter("denunciaid", denunciaid) :
                new ObjectParameter("denunciaid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_mostar_denuncias_comentario_Result>("f_mostar_denuncias_comentario", denunciaidParameter);
        }
    
        public virtual int f_agregar_control(string control, Nullable<int> formulario)
        {
            var controlParameter = control != null ?
                new ObjectParameter("control", control) :
                new ObjectParameter("control", typeof(string));
    
            var formularioParameter = formulario.HasValue ?
                new ObjectParameter("formulario", formulario) :
                new ObjectParameter("formulario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_agregar_control", controlParameter, formularioParameter);
        }
    
        public virtual ObjectResult<f_cargar_idiomas_Result> f_cargar_idiomas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_cargar_idiomas_Result>("f_cargar_idiomas");
        }
    
        public virtual int f_ingresar_idioma(string idioma, string cultura)
        {
            var idiomaParameter = idioma != null ?
                new ObjectParameter("idioma", idioma) :
                new ObjectParameter("idioma", typeof(string));
    
            var culturaParameter = cultura != null ?
                new ObjectParameter("cultura", cultura) :
                new ObjectParameter("cultura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_ingresar_idioma", idiomaParameter, culturaParameter);
        }
    
        public virtual int f_ingresar_idioma_control(Nullable<int> idioma, string control, Nullable<int> formulario, string valor)
        {
            var idiomaParameter = idioma.HasValue ?
                new ObjectParameter("idioma", idioma) :
                new ObjectParameter("idioma", typeof(int));
    
            var controlParameter = control != null ?
                new ObjectParameter("control", control) :
                new ObjectParameter("control", typeof(string));
    
            var formularioParameter = formulario.HasValue ?
                new ObjectParameter("formulario", formulario) :
                new ObjectParameter("formulario", typeof(int));
    
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_ingresar_idioma_control", idiomaParameter, controlParameter, formularioParameter, valorParameter);
        }
    
        public virtual ObjectResult<f_listar_controles_Result> f_listar_controles(Nullable<int> formulario)
        {
            var formularioParameter = formulario.HasValue ?
                new ObjectParameter("formulario", formulario) :
                new ObjectParameter("formulario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_controles_Result>("f_listar_controles", formularioParameter);
        }
    
        public virtual ObjectResult<f_listar_controles2_Result> f_listar_controles2(Nullable<int> formulario, Nullable<int> idioma)
        {
            var formularioParameter = formulario.HasValue ?
                new ObjectParameter("formulario", formulario) :
                new ObjectParameter("formulario", typeof(int));
    
            var idiomaParameter = idioma.HasValue ?
                new ObjectParameter("idioma", idioma) :
                new ObjectParameter("idioma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_controles2_Result>("f_listar_controles2", formularioParameter, idiomaParameter);
        }
    
        public virtual ObjectResult<f_listar_formulario_Result> f_listar_formulario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_formulario_Result>("f_listar_formulario");
        }
    
        public virtual ObjectResult<f_obtener_idioma_formulario_Result> f_obtener_idioma_formulario(Nullable<int> formulario_id, Nullable<int> idioma_id)
        {
            var formulario_idParameter = formulario_id.HasValue ?
                new ObjectParameter("formulario_id", formulario_id) :
                new ObjectParameter("formulario_id", typeof(int));
    
            var idioma_idParameter = idioma_id.HasValue ?
                new ObjectParameter("idioma_id", idioma_id) :
                new ObjectParameter("idioma_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_obtener_idioma_formulario_Result>("f_obtener_idioma_formulario", formulario_idParameter, idioma_idParameter);
        }
    
        public virtual int f_update_idioma_control(Nullable<int> control, string valor)
        {
            var controlParameter = control.HasValue ?
                new ObjectParameter("control", control) :
                new ObjectParameter("control", typeof(int));
    
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_update_idioma_control", controlParameter, valorParameter);
        }
    
        public virtual ObjectResult<f_busqueda_Result> f_busqueda(string dato)
        {
            var datoParameter = dato != null ?
                new ObjectParameter("dato", dato) :
                new ObjectParameter("dato", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_busqueda_Result>("f_busqueda", datoParameter);
        }
    
        public virtual ObjectResult<f_busqueda_private_Result> f_busqueda_private(string dato)
        {
            var datoParameter = dato != null ?
                new ObjectParameter("dato", dato) :
                new ObjectParameter("dato", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_busqueda_private_Result>("f_busqueda_private", datoParameter);
        }
    
        public virtual ObjectResult<f_cargar_mod_post_Result> f_cargar_mod_post(Nullable<int> userid, Nullable<int> postid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var postidParameter = postid.HasValue ?
                new ObjectParameter("postid", postid) :
                new ObjectParameter("postid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_cargar_mod_post_Result>("f_cargar_mod_post", useridParameter, postidParameter);
        }
    
        public virtual ObjectResult<string> f_comentar_post(Nullable<int> comentarioid, Nullable<int> userid, Nullable<int> postid, string comentario)
        {
            var comentarioidParameter = comentarioid.HasValue ?
                new ObjectParameter("comentarioid", comentarioid) :
                new ObjectParameter("comentarioid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var postidParameter = postid.HasValue ?
                new ObjectParameter("postid", postid) :
                new ObjectParameter("postid", typeof(int));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("comentario", comentario) :
                new ObjectParameter("comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_comentar_post", comentarioidParameter, useridParameter, postidParameter, comentarioParameter);
        }
    
        public virtual ObjectResult<string> f_ingresar_post(string sesion, Nullable<int> userid, string nombre, string descripcion, Nullable<int> categoria, string contenido, string autor, string miniatura, string etiquetas)
        {
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var categoriaParameter = categoria.HasValue ?
                new ObjectParameter("categoria", categoria) :
                new ObjectParameter("categoria", typeof(int));
    
            var contenidoParameter = contenido != null ?
                new ObjectParameter("contenido", contenido) :
                new ObjectParameter("contenido", typeof(string));
    
            var autorParameter = autor != null ?
                new ObjectParameter("autor", autor) :
                new ObjectParameter("autor", typeof(string));
    
            var miniaturaParameter = miniatura != null ?
                new ObjectParameter("miniatura", miniatura) :
                new ObjectParameter("miniatura", typeof(string));
    
            var etiquetasParameter = etiquetas != null ?
                new ObjectParameter("etiquetas", etiquetas) :
                new ObjectParameter("etiquetas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_ingresar_post", sesionParameter, useridParameter, nombreParameter, descripcionParameter, categoriaParameter, contenidoParameter, autorParameter, miniaturaParameter, etiquetasParameter);
        }
    
        public virtual ObjectResult<string> f_ingresar_post_privado(string sesion, Nullable<int> userid, string nombre, string descripcion, Nullable<int> categoria, string contenido, string autor, string miniatura, string etiquetas)
        {
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var categoriaParameter = categoria.HasValue ?
                new ObjectParameter("categoria", categoria) :
                new ObjectParameter("categoria", typeof(int));
    
            var contenidoParameter = contenido != null ?
                new ObjectParameter("contenido", contenido) :
                new ObjectParameter("contenido", typeof(string));
    
            var autorParameter = autor != null ?
                new ObjectParameter("autor", autor) :
                new ObjectParameter("autor", typeof(string));
    
            var miniaturaParameter = miniatura != null ?
                new ObjectParameter("miniatura", miniatura) :
                new ObjectParameter("miniatura", typeof(string));
    
            var etiquetasParameter = etiquetas != null ?
                new ObjectParameter("etiquetas", etiquetas) :
                new ObjectParameter("etiquetas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_ingresar_post_privado", sesionParameter, useridParameter, nombreParameter, descripcionParameter, categoriaParameter, contenidoParameter, autorParameter, miniaturaParameter, etiquetasParameter);
        }
    
        public virtual ObjectResult<string> f_ingreso_categoria(string nombre, string descripcion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_ingreso_categoria", nombreParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<f_listar_categoria_Result> f_listar_categoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_categoria_Result>("f_listar_categoria");
        }
    
        public virtual ObjectResult<f_listar_comentarios_post_Result> f_listar_comentarios_post(Nullable<long> postid, Nullable<int> comentario)
        {
            var postidParameter = postid.HasValue ?
                new ObjectParameter("postid", postid) :
                new ObjectParameter("postid", typeof(long));
    
            var comentarioParameter = comentario.HasValue ?
                new ObjectParameter("comentario", comentario) :
                new ObjectParameter("comentario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_comentarios_post_Result>("f_listar_comentarios_post", postidParameter, comentarioParameter);
        }
    
        public virtual ObjectResult<f_listar_post_Result> f_listar_post(string sesion, Nullable<int> userid)
        {
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_post_Result>("f_listar_post", sesionParameter, useridParameter);
        }
    
        public virtual ObjectResult<f_listar_post_home_Result> f_listar_post_home(string orden)
        {
            var ordenParameter = orden != null ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_post_home_Result>("f_listar_post_home", ordenParameter);
        }
    
        public virtual ObjectResult<f_listar_post_home_categorias_Result> f_listar_post_home_categorias(string orden)
        {
            var ordenParameter = orden != null ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_post_home_categorias_Result>("f_listar_post_home_categorias", ordenParameter);
        }
    
        public virtual ObjectResult<f_listar_post_home_categorias_private_Result> f_listar_post_home_categorias_private(string orden)
        {
            var ordenParameter = orden != null ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_post_home_categorias_private_Result>("f_listar_post_home_categorias_private", ordenParameter);
        }
    
        public virtual ObjectResult<f_listar_post_home_private_Result> f_listar_post_home_private(string orden)
        {
            var ordenParameter = orden != null ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_post_home_private_Result>("f_listar_post_home_private", ordenParameter);
        }
    
        public virtual ObjectResult<f_listar_post_home_servicios_Result> f_listar_post_home_servicios(string orden)
        {
            var ordenParameter = orden != null ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_post_home_servicios_Result>("f_listar_post_home_servicios", ordenParameter);
        }
    
        public virtual ObjectResult<f_listar_post_moderador_Result> f_listar_post_moderador(string orden)
        {
            var ordenParameter = orden != null ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_post_moderador_Result>("f_listar_post_moderador", ordenParameter);
        }
    
        public virtual ObjectResult<f_listar_post_private_Result> f_listar_post_private(string sesion, Nullable<int> userid)
        {
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_post_private_Result>("f_listar_post_private", sesionParameter, useridParameter);
        }
    
        public virtual ObjectResult<f_listar_post_public_Result> f_listar_post_public(string sesion, Nullable<int> userid)
        {
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_listar_post_public_Result>("f_listar_post_public", sesionParameter, useridParameter);
        }
    
        public virtual ObjectResult<string> f_modificar_post(string sesion, Nullable<int> postid, Nullable<int> userid, string nombre, string descripcion, Nullable<int> categoria, string contenido, string autor, string miniatura, string etiquetas)
        {
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            var postidParameter = postid.HasValue ?
                new ObjectParameter("postid", postid) :
                new ObjectParameter("postid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var categoriaParameter = categoria.HasValue ?
                new ObjectParameter("categoria", categoria) :
                new ObjectParameter("categoria", typeof(int));
    
            var contenidoParameter = contenido != null ?
                new ObjectParameter("contenido", contenido) :
                new ObjectParameter("contenido", typeof(string));
    
            var autorParameter = autor != null ?
                new ObjectParameter("autor", autor) :
                new ObjectParameter("autor", typeof(string));
    
            var miniaturaParameter = miniatura != null ?
                new ObjectParameter("miniatura", miniatura) :
                new ObjectParameter("miniatura", typeof(string));
    
            var etiquetasParameter = etiquetas != null ?
                new ObjectParameter("etiquetas", etiquetas) :
                new ObjectParameter("etiquetas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_modificar_post", sesionParameter, postidParameter, useridParameter, nombreParameter, descripcionParameter, categoriaParameter, contenidoParameter, autorParameter, miniaturaParameter, etiquetasParameter);
        }
    
        public virtual ObjectResult<string> f_puntuar_post(Nullable<int> puntuacion, Nullable<int> userid, Nullable<int> postid)
        {
            var puntuacionParameter = puntuacion.HasValue ?
                new ObjectParameter("puntuacion", puntuacion) :
                new ObjectParameter("puntuacion", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var postidParameter = postid.HasValue ?
                new ObjectParameter("postid", postid) :
                new ObjectParameter("postid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_puntuar_post", puntuacionParameter, useridParameter, postidParameter);
        }
    
        public virtual ObjectResult<string> f_suspender_post(string sesion, Nullable<int> postid)
        {
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            var postidParameter = postid.HasValue ?
                new ObjectParameter("postid", postid) :
                new ObjectParameter("postid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_suspender_post", sesionParameter, postidParameter);
        }
    
        public virtual ObjectResult<string> f_validar_post(string sesion, Nullable<int> postid)
        {
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            var postidParameter = postid.HasValue ?
                new ObjectParameter("postid", postid) :
                new ObjectParameter("postid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_validar_post", sesionParameter, postidParameter);
        }
    
        public virtual ObjectResult<f_ver_post_Result> f_ver_post(Nullable<long> postid, Nullable<int> control)
        {
            var postidParameter = postid.HasValue ?
                new ObjectParameter("postid", postid) :
                new ObjectParameter("postid", typeof(long));
    
            var controlParameter = control.HasValue ?
                new ObjectParameter("control", control) :
                new ObjectParameter("control", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_ver_post_Result>("f_ver_post", postidParameter, controlParameter);
        }
    
        public virtual ObjectResult<f_ver_post2_Result> f_ver_post2(Nullable<int> postid)
        {
            var postidParameter = postid.HasValue ?
                new ObjectParameter("postid", postid) :
                new ObjectParameter("postid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_ver_post2_Result>("f_ver_post2", postidParameter);
        }
    
        public virtual int f_visita_post(Nullable<int> postid)
        {
            var postidParameter = postid.HasValue ?
                new ObjectParameter("postid", postid) :
                new ObjectParameter("postid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_visita_post", postidParameter);
        }
    
        public virtual ObjectResult<f_reporte_publicacion_Result> f_reporte_publicacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_reporte_publicacion_Result>("f_reporte_publicacion");
        }
    
        public virtual ObjectResult<f_reporte_puntuacion_Result> f_reporte_puntuacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_reporte_puntuacion_Result>("f_reporte_puntuacion");
        }
    
        public virtual ObjectResult<f_reporte_usuario_Result> f_reporte_usuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_reporte_usuario_Result>("f_reporte_usuario");
        }
    
        public virtual int f_actualizar_bloqueo_sesion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_actualizar_bloqueo_sesion");
        }
    
        public virtual int f_actualizar_bloqueo_sesion2(string session)
        {
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_actualizar_bloqueo_sesion2", sessionParameter);
        }
    
        public virtual int f_actualizar_bloqueo_sesiones(string username, Nullable<int> nsesion)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var nsesionParameter = nsesion.HasValue ?
                new ObjectParameter("nsesion", nsesion) :
                new ObjectParameter("nsesion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_actualizar_bloqueo_sesiones", usernameParameter, nsesionParameter);
        }
    
        public virtual int f_actualizar_estado(string p_user_name)
        {
            var p_user_nameParameter = p_user_name != null ?
                new ObjectParameter("p_user_name", p_user_name) :
                new ObjectParameter("p_user_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_actualizar_estado", p_user_nameParameter);
        }
    
        public virtual int f_almacenar_token(string token, Nullable<int> user_id)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_almacenar_token", tokenParameter, user_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> f_cambiar_password(string password, string token)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("f_cambiar_password", passwordParameter, tokenParameter);
        }
    
        public virtual int f_ingresar_bloqueo_sesion(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_ingresar_bloqueo_sesion", usernameParameter);
        }
    
        public virtual ObjectResult<string> f_ingresar_correo_institucional(Nullable<int> userid, string correo, string session)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_ingresar_correo_institucional", useridParameter, correoParameter, sessionParameter);
        }
    
        public virtual int f_limpiar_bloqueo(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_limpiar_bloqueo", usernameParameter);
        }
    
        public virtual ObjectResult<string> f_modificar_perfil_ajustes1(string session, Nullable<int> userid, string username, string correo, string contrasena)
        {
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_modificar_perfil_ajustes1", sessionParameter, useridParameter, usernameParameter, correoParameter, contrasenaParameter);
        }
    
        public virtual ObjectResult<string> f_solicitar_bloqueo(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_solicitar_bloqueo", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> f_solicitar_bloqueo_preingreso(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("f_solicitar_bloqueo_preingreso", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> f_solicitar_bloqueo_sesiones(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("f_solicitar_bloqueo_sesiones", idParameter);
        }
    
        public virtual ObjectResult<f_solicitar_bloqueo2_Result> f_solicitar_bloqueo2(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_solicitar_bloqueo2_Result>("f_solicitar_bloqueo2", usernameParameter);
        }
    
        public virtual ObjectResult<string> f_solicitar_contador_sesiones(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_solicitar_contador_sesiones", usernameParameter);
        }
    
        public virtual ObjectResult<string> f_traer_correo_institucional(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_traer_correo_institucional", useridParameter);
        }
    
        public virtual ObjectResult<f_traer_datos_Result> f_traer_datos(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_traer_datos_Result>("f_traer_datos", useridParameter);
        }
    
        public virtual ObjectResult<f_traer_datos_sesion1_Result> f_traer_datos_sesion1(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_traer_datos_sesion1_Result>("f_traer_datos_sesion1", useridParameter);
        }
    
        public virtual ObjectResult<f_traer_datos_sesion2_Result> f_traer_datos_sesion2(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_traer_datos_sesion2_Result>("f_traer_datos_sesion2", useridParameter);
        }
    
        public virtual ObjectResult<f_traer_datos_vista_perfil_Result> f_traer_datos_vista_perfil(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_traer_datos_vista_perfil_Result>("f_traer_datos_vista_perfil", useridParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> f_validar_token(string token)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("f_validar_token", tokenParameter);
        }
    
        public virtual ObjectResult<f_validar_usuario_Result> f_validar_usuario(string user_name)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_validar_usuario_Result>("f_validar_usuario", user_nameParameter);
        }
    }
}
