//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingresos
    {
        public long id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_mac { get; set; }
        public string user_session { get; set; }
        public Nullable<System.TimeSpan> fecha_inicio { get; set; }
        public Nullable<System.TimeSpan> fecha_fin { get; set; }
        public string user_ip { get; set; }
    }
}
