//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public long id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string avatar { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<long> id_session { get; set; }
        public string sexo { get; set; }
        public string session { get; set; }
    
        public virtual user_session user_session { get; set; }
    }
}
