//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Tilitarios;
    
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<denuncia_comentario> denuncia_comentario { get; set; }
        public virtual DbSet<denuncia_publicacion> denuncia_publicacion { get; set; }
        public virtual DbSet<estado_denuncia> estado_denuncia { get; set; }
        public virtual DbSet<controle> controles { get; set; }
        public virtual DbSet<formulario> formularios { get; set; }
        public virtual DbSet<idioma> idiomas { get; set; }
        public virtual DbSet<lcontrole> lcontroles { get; set; }
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<comentario> comentarios { get; set; }
        public virtual DbSet<estado> estadoes { get; set; }
        public virtual DbSet<publicacion> publicacions { get; set; }
        public virtual DbSet<puntuacion> puntuacions { get; set; }
        public virtual DbSet<contacto> contactoes { get; set; }
        public virtual DbSet<auditoria> auditorias { get; set; }
        public virtual DbSet<bloqueo_configuration> bloqueo_configuration { get; set; }
        public virtual DbSet<ingreso> ingresos { get; set; }
        public virtual DbSet<bloqueo> bloqueos { get; set; }
        public virtual DbSet<correo_institucional> correo_institucional { get; set; }
        public virtual DbSet<estado1> estado1 { get; set; }
        public virtual DbSet<permiso> permisos { get; set; }
        public virtual DbSet<user_session> user_session { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
